block_size: 1024
validation_split_percentage: 5
dataset_percentage: 100
seed: 42
streaming: false
preprocessing_num_workers: 4
load_from_disk: false
learning_rate: 1.0e-6
num_train_epochs: 2
per_device_train_batch_size: 4
per_device_eval_batch_size: 1
gradient_accumulation_steps: 4
gradient_checkpointing: false
max_steps: -1
save_strategy: "no"
save_steps: 1
evaluation_strategy: "no"
eval_steps: 1
weight_decay: 0.01
warmup_ratio: 0.05
warmup_steps: 0
lr_scheduler_type: "linear"
logging_steps: 1
do_train: true
do_eval: false
