name: ""

## COT & RAG
use_cot: True
use_init_context: False
num_documents: 0
use_corr_context: False

num_iterations: 2

## STASC Parameter
fixed_initialization: False
improving_filter: False
fixed_fine_tuning: False
number_corrections: 3

finalize_judgement: False

num_refine_iterations: 5
