model:
  model_name_or_path: "VityaVitalich/Llama3.1-8b-instruct"
  tokenizer_name: null
  cache_dir: "/home/data/v.moskvoretskii/cache/"
  trust_remote_code: true
  use_fast_tokenizer: true
  torch_dtype: "float16"

data:
  dataset_name: "data/datasets/s_nq"
  block_size: 8192
  validation_split_percentage: 0
  dataset_percentage: 100
  seed: 42
  streaming: false
  overwrite_cache: false
  preprocessing_num_workers: 4
  load_from_disk: true

training:
  output_dir: "./my-finetuned-llama-fsdp"
  learning_rate: 1.0e-4
  num_train_epochs: 3
  per_device_train_batch_size: 2
  per_device_eval_batch_size: 2
  gradient_accumulation_steps: 4
  gradient_checkpointing: false
  max_steps: -1
  save_strategy: "steps"
  save_steps: 500
  evaluation_strategy: "steps"
  eval_steps: 500
  weight_decay: 0.1
  warmup_ratio: 0.03
  lr_scheduler_type: "cosine"
  logging_steps: 10
  do_train: true
  do_eval: true
  report_to: ["tensorboard"]
  run_name: "llama3.1-8b-ft-fsdp"

  # FSDP-specific arguments
  fsdp: "full_shard auto_wrap"
  fsdp_min_num_params: 20000

peft:
  use_lora: true
  lora_rank: 8
  lora_alpha: 16
  lora_dropout: 0.1
  lora_target_modules:
    - "query_key_value"
  dora: false
