
# Model Configuration
model_path: "Qwen/Qwen2.5-Math-1.5B-Instruct" #'microsoft/Phi-3-mini-4k-instruct' # "Qwen/Qwen2.5-1.5B-Instruct" # "Qwen/Qwen2.5-Math-1.5B-Instruct"
cache_dir: "/home/data/v.moskvoretskii/cache/"
random_seed: 42
wandb_project_name: 'SCoRE'

# Dataset Configuration 
task_type: "math" # "qa" or "math"
data_path: "data/datasets/math500"
id_col: "unique_id"                        # Unique identifier column in the dataset. "question_id" for QA, "problem" for "unique_id"
question_col: "problem"            # Column containing the question text. "question_text" for QA, "problem" for math500
gold_col: "answer"                   # Reference/GT answer column. "reference" for QA, "answer" for math500

run_name: "test_score_math"

# Reward Function
evaluator_mode: 'final'   # "default" will input all answer in reward func, "final" only string after "evaluator_answer_marker"
evaluator_function: 'math_acc' # metric function to use, in_acc, f1, em for QA, "math_acc" for math500. math500 always has "final" evaluation mode
evaluator_answer_marker: 'Final Answer: The final answer is' # the key word to find answer after. truncates answer untils this phrase. Case insensetive. 
# "Final Answer: The final answer is" for math
# "Final Answer:" for qa
 
# Generation Configuration
few_shot_dir: "few_shots"            # Directory containing few-shot JSON files
number_output_initial_generations: 1         

# Sampling Parameters
temperature: 0.7                    # Sampling temperature
max_tokens: 2048                     # Maximum number of tokens to generate

# total batch = per_device_train_batch_size * num_gpus * gradient_accumulation_steps
per_device_train_batch_size: 1
gradient_accumulation_steps: 1
total_episodes: 1000 # number of train samples seen. number of gradient steps = total_episodes / total batch 
learning_rate: 5.0e-5
num_warmup_steps: 10 # number of warmup steps in scheduler
kl_coef: 0.2
