num_star_iterations: 5
run_name_specification: ''
initial_answer_with_new_model: true
only_better_correction: false
train_from_initial_model: true
number_output_initial_generations: 1
number_output_corrections: 3
